### ISSUE TITLE
error parsing CSV: wrong amount of columns for frame: 1: `---`

### ISSUE THREAD

**Issue by Bloona** [teran/eos-1v-tagger#2]
**Describe the bug**
When I call tagger.exe in cmd I get the error message
`error parsing CSV: wrong amount of columns for frame: 1: ´---´
`

**To Reproduce**
1. c:\Tagger>eos-1v-tagger.exe config.yaml 2021-04-30_EOS_1V.CSV >exiftoool-commands.bat

**Expected behavior**
I would expect the program to generate the output file
`exiftool-commands.bat`

**Screenshots**
-/-

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1151
 - ES-E1 EOS Link Software 1.30
 - eos-1v-tagger 0.1-alpha.28, build with go1.13.6 at 2020-01-21T22:42:16+01:00

**Attachments**
Please attach all applicable files to reproduce the issue. It could be:
* CSV from ES-E1
* config.yaml

[Tagger.zip](https://github.com/teran/eos-1v-tagger/files/7026131/Tagger.zip)

**Comment by teran** [comment]
Hello @Bloona

Thanks for using tagger!

Based on the error message and how you're running tagger your issue is about wrong argumens: `config.yml` should be simply placed to `${HOMEDIR}/.tagger/config.yaml` which is normally `C:\Users\<username>\.tagger\config.yaml` on Windows and it should **not** be passed as tagger argument - only CSV file is required (I've set `--timestamp-format` since I have US format on my macOS, you probably don't need it):

```
eos-1v-tagger -timestamp-format=EU /Users/teran/Downloads/Tagger/2021-04-30_EOS_1V.CSV  | head -n1
exiftool .....
```

i.e. your CSV file is fine and works well, simply move `config.yaml` to `C:\Users\<username>\.tagger\config.yaml` and try running tagger the following way:

```
eos-1v-tagger.exe 2021-04-30_EOS_1V.CSV >exiftoool-commands.bat
```

There are more details on Wiki: https://github.com/teran/eos-1v-tagger/wiki/Usage
Note all the parameters from `config.yaml` could be utilized via options to tagger binary.

Hope this will help and please let me know if you have any questions :)

**Comment by Bloona** [comment]
Hello Igor,
thank you for your support. Works like charm now!


Am 21.08.2021 um 22:58 schrieb Igor Shishkin ***@***.***>:


﻿

Hello @Bloona

Thanks for using tagger!

Based on the error message and how you're running tagger your issue is about wrong argumens: config.yml should be simply placed to ${HOMEDIR}/.tagger/config.yaml which is normally C:\Users\<username>\.tagger\config.yaml on Windows and it should not be passed as tagger argument - only CSV file is required (I've set --timestamp-format since I have US format on my macOS, you should probably don't need it):



eos-1v-tagger -timestamp-format=EU /Users/teran/Downloads/Tagger/2021-04-30_EOS_1V.CSV  | head -n1
exiftool .....


i.e. your CSV file is fine and works well, simply move config.yaml to C:\Users\<username>\.tagger\config.yaml and try running tagger the following way:



eos-1v-tagger.exe 2021-04-30_EOS_1V.CSV >exiftoool-commands.bat


There are more details on Wiki: https://github.com/teran/eos-1v-tagger/wiki/Usage
Note all the parameters from config.yaml could be utilized via options to tagger binary.

Hope this will help and please let me know if you have any questions :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by teran** [comment]
Glad to hear that :)
